version: '3.7'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongorootpwd
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '1025:1025' # SMTP port for sending emails
      - '8025:8025' # Web UI port for viewing emails
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 'true'
      MP_SMTP_AUTH_ALLOW_INSECURE: 'true'
    volumes:
      - mailpit_data:/data

volumes:
  mongodb_data:
  mailpit_data:
